/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function version(): string
export type JsVector3 = Vector3
export declare class Vector3 {
  x: number
  y: number
  z: number
  constructor(x?: number | undefined | null, y?: number | undefined | null, z?: number | undefined | null)
  length(): number
  normalized(): Vector3
}
export type JsColor = Color
export declare class Color {
  r: number
  g: number
  b: number
  constructor(r?: number | undefined | null, g?: number | undefined | null, b?: number | undefined | null)
  static fromHex(hex: number): JsColor
}
export type JsPerspectiveCamera = PerspectiveCamera
export declare class PerspectiveCamera {
  constructor(fov?: number | undefined | null, aspect?: number | undefined | null, near?: number | undefined | null, far?: number | undefined | null)
  setPosition(x: number, y: number, z: number): void
  lookAt(x: number, y: number, z: number): void
  setAspect(aspect: number): void
}
export type JsScene = Scene
export declare class Scene {
  constructor()
  /** Add an axis-aligned box mesh. Returns a stable handle index. */
  addBox(width?: number | undefined | null, height?: number | undefined | null, depth?: number | undefined | null, color?: number | undefined | null, x?: number | undefined | null, y?: number | undefined | null, z?: number | undefined | null): number
  addSphere(radius?: number | undefined | null, color?: number | undefined | null, x?: number | undefined | null, y?: number | undefined | null, z?: number | undefined | null): number
  setBackground(hex: number): void
  setPosition(handle: number, x: number, y: number, z: number): void
  objectCount(): number
}
export type JsHeadlessRenderer = HeadlessRenderer
export declare class HeadlessRenderer {
  constructor(width?: number | undefined | null, height?: number | undefined | null, supersample?: number | undefined | null)
  /** Render and return tightly packed RGBA8 bytes (`width * height * 4`). */
  renderRgba(scene: Scene, camera: PerspectiveCamera): Buffer
  /** Render and return a PNG as bytes. */
  renderPng(scene: Scene, camera: PerspectiveCamera): Buffer
  size(): Array<number>
}
export type JsTween = Tween
export declare class Tween {
  constructor(start?: number | undefined | null, end?: number | undefined | null, duration?: number | undefined | null, easing?: string | undefined | null)
  update(dt: number): number
  value(): number
  isFinished(): boolean
}
export type JsPhysicsWorld = PhysicsWorld
export declare class PhysicsWorld {
  constructor()
  /** Add a dynamic ball. Returns a stable handle index. */
  addBall(radius?: number | undefined | null, x?: number | undefined | null, y?: number | undefined | null, z?: number | undefined | null, restitution?: number | undefined | null): number
  step(dt: number): void
  bodyTranslation(handle: number): Vector3
  bodyCount(): number
}
